CC = gcc
CFLAGS = -std=gnu99 -Wall -Wextra

all: prog tolower

prog: prog.c  
#$(CC) $(CFLAGS) prog.c -o prog

tolower: tolower.c
#$(CC) $(CFLAGS) tolower.c -o tolower

clean:
	rm -f *.o prog tolower
