zadanie2: zadanie2.ml
	ocamlc zadanie2.ml -o zadanie2
	export OCAMLRUNPARAM='l=256M'

zadanie4: zadanie4.ml
	ocamlc zadanie4.ml -o zadanie4
	export OCAMLRUNPARAM='l=256M'

clean:
	rm zadanie*.cm* zadanie2 zadanie4