CXXFLAGS = -std=c++11 -O2
CXX = g++

wood: wood.cpp
	$(CXX) $(CXXFLAGS) -o wood wood.cpp

silver: silver.cpp
	$(CXX) $(CXXFLAGS) -o silver silver.cpp

gold: gold.cpp
	$(CXX) $(CXXFLAGS) -o gold gold.cpp

legend: legend.cpp
	$(CXX) $(CXXFLAGS) -o legend legend.cpp

clean:
	rm wood silver gold legend
