/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WhatsThePoint;

import javax.swing.JDialog;
import javax.swing.JOptionPane;


/**
 *
 * @author Dziku
 */
public class GameView extends View {


    /**
     * Creates new form GameView
     */
    public GameView() {

    }
    
    @Override
    public void initialize()
    {
        initComponents();
    }
    
 
    @Override
    public void repaint()
    {
        //System.out.println("Kappa");
        super.repaint();
        //gameArea.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        segmentsLabel = new javax.swing.JLabel();
        numberOfSegmentsLabel = new javax.swing.JLabel();
        retryButton = new javax.swing.JButton();
        returnToMenuButton = new javax.swing.JButton();
        gameArea = new GameArea(model);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        segmentsLabel.setFont(new java.awt.Font("SketchFlow Print", 1, 30)); // NOI18N
        segmentsLabel.setText("Segments:");

        numberOfSegmentsLabel.setFont(new java.awt.Font("SketchFlow Print", 1, 48)); // NOI18N
        numberOfSegmentsLabel.setText("0");

        retryButton.setFont(new java.awt.Font("SketchFlow Print", 0, 24)); // NOI18N
        retryButton.setText("Retry");
        retryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retryButtonActionPerformed(evt);
            }
        });

        returnToMenuButton.setFont(new java.awt.Font("SketchFlow Print", 0, 24)); // NOI18N
        returnToMenuButton.setText("Menu");
        returnToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMenuButtonActionPerformed(evt);
            }
        });

        gameArea.setBackground(new java.awt.Color(255, 255, 255));
        gameArea.setMaximumSize(new java.awt.Dimension(600, 600));
        gameArea.setMinimumSize(new java.awt.Dimension(600, 600));
        gameArea.setPreferredSize(new java.awt.Dimension(600, 600));
        gameArea.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                gameAreaMouseMoved(evt);
            }
        });
        gameArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameAreaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gameAreaLayout = new javax.swing.GroupLayout(gameArea);
        gameArea.setLayout(gameAreaLayout);
        gameAreaLayout.setHorizontalGroup(
            gameAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        gameAreaLayout.setVerticalGroup(
            gameAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(returnToMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(numberOfSegmentsLabel)
                        .addGap(67, 67, 67))
                    .addComponent(segmentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(segmentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numberOfSegmentsLabel)
                .addGap(58, 58, 58)
                .addComponent(retryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(returnToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void retryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retryButtonActionPerformed
        //Application.getInstance().setNewState(new GameModel(), new GameView());
        model.initialize();
        updateSegmentsCounter();
    }//GEN-LAST:event_retryButtonActionPerformed

    private void returnToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMenuButtonActionPerformed
        Application.getInstance().setNewState(new MainMenuModel(), new MainMenuView());
    }//GEN-LAST:event_returnToMenuButtonActionPerformed

    private void gameAreaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameAreaMouseMoved
        model.mousePositionChanged(evt.getX(), evt.getY());
    }//GEN-LAST:event_gameAreaMouseMoved

    private void gameAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameAreaMouseClicked
        model.mouseClicked();
        updateSegmentsCounter();
        
    }//GEN-LAST:event_gameAreaMouseClicked

    public void updateSegmentsCounter()
    {
        int howMany = model.getInfo();
        //int howMany = Integer.parseInt(numberOfSegmentsLabel.getText());
        numberOfSegmentsLabel.setText(Integer.toString(howMany));
    }
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameArea;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel numberOfSegmentsLabel;
    private javax.swing.JButton retryButton;
    private javax.swing.JButton returnToMenuButton;
    private javax.swing.JLabel segmentsLabel;
    // End of variables declaration//GEN-END:variables

}
